CREATE TABLE dbo.Member
(
	MemberID INT IDENTITY(1,1) NOT NULL,
	Username VARCHAR(12) DEFAULT('') NOT NULL,
	UserPassword VARCHAR(32) DEFAULT('') NOT NULL,
	IsActive BIT DEFAULT(0) NOT NULL
)
GO
ALTER TABLE dbo.Member ADD CONSTRAINT pk_Member PRIMARY KEY CLUSTERED (MemberID)
GO